config/routes.rb
Rails.application.routes.draw do

 get "physicians_see_patients/:id" => "physicians#see_patients" 

 get "patients_patient_details/:id" => "patients#patient_details"

 get "order" => "orders#index"

 get "/export_xml" => "appointments#export_to_xml"

 post "/export_ajax" => "appointments#export_ajax"

 post "/to_check" => "appointments#to_check"

 post "/to_clear_it" => "appointments#to_clear_it"

 get 'check' => "physicians#check", :as => :let_me_check

resources :appointments
resources :patients
resources :physicians

root to: "welcome#index"

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
belongs_to :patient
belongs_to :physician
end

app/models/patient.rb
class Patient < ActiveRecord::Base


has_many :appointments
has_many :physicians, through: :appointments
belongs_to :ward

  searchable do

    string  :name, :problem

 #     problem.downcase.gsub(/^(an?|the)/, '')

  end

  def self.delete_file
    `rm #{Rails.root}/public/text.csv`
  end
end

app/models/physician.rb
class Physician < ActiveRecord::Base

extend FriendlyId

friendly_id :name, use: :slugged
has_many :appointments
has_many :patients, through: :appointments
end

app/models/ward.rb
class Ward < ActiveRecord::Base
  has_many :patients

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  respond_to :xml, :json, :html
  def index
    debugger
    @appointments = Appointment.all
    respond_to do |format|
      format.xml {  render :layout => false, :template => "appointments/index.xml" }

    end
  end

  def export_ajax
    email = "akshay@kreatio.com"
    filename = "check101"
    render :json => {"email_status" => email, "file_name" => filename }.to_json
  end

  def to_check
    email = "akshay@kreatio.com"
    filename = "check101"
    render :json => {"email_status" => email, "file_name" => filename }.to_json
  end

  def to_clear_it
    email = "akshay@kreatio.com"
    filename = "check101"
    status = true
    render :json => {"email_status" => email, "file_name" => filename, "status" => true}.to_json
  end

  def new_doc
    doc =  Docx::Document.new('you.docx')
    doc.bookmarks().merge!({"aksh" => "check"})
  end
  # @appointments=Appointment.all.paginate(:page => params[:page], :per_page => 4)
  #@appointments=Appointment.last(10).paginate(:page => params[:page], :per_page => 2)
end

# def export_to_xml
#   @appointments = Appointment.all
#   # byebug
#   # send_file @appointments, filename: 'abc.xml'
# end
# end

app/controllers/associates_controller.rb
class AssociatesController < ApplicationController

def index

end


def new
@asso = Association.new
end

def create
@asso = Association.new
@asso.physician_id = params[:association][:physician_id]

@asso.save
end

def show

end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def index

  end

  def status

  end

end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  respond_to :html, :json
  def index
    @patients=Patient.all
#    @search = Patient.search { keywords params[:search]}

  #  @patients = @search.results
  end
  
  def new
    @patient=Patient.new
  end
  #Patient.find_or_create_by(name: 'aksjkjhkhk') do |check|

  def create
     @patient=Patient.new(patient_params)
#    @patient.name = params[:patient][:name]
#    @patient.problem =params[:patient][:problem]
     #@patient.select_physician =params[:physician][:physician_id]
#    if @patient.save

#    redirect_to @patient

    if @patient.save
      @appointment=Appointment.new()
      @appointment.patient_id= @patient.id
      #@appointment.physician_id= params[:physician][:physician_id]
      @appointment.appointment_date
      @appointment.save
#      UserMailer.delay.registration_confirmation(@patient)
#      format.html { redirect_to(@patient, :notice => 'User was successfully created.') }
#      format.xml  { render :xml => @patient, :status => :created, :location => @patient }
    else
 #     format.html { render :action => "new" }
  #    format.xml  { render :xml => @patient.errors, :status => :unprocessable_entity }
    end
  end




#    else
#    render 'new'
#    end

  def edit
    @patient = Patient.find(params[:id])
  end


  def update

    @patient = Patient.find(params[:id])
    # if @patient.save
    #   @appointment=Appointment.new()
    #   @appointment.patient_id= @patient.id
    #   @appointment.physician_id= params[:physician][:physician_id]
    #   @appointment.appointment_date
    #   @appointment.save
    @patient.update_attributes(patient_params)
    respond_with @patient
  end

  def show
    @patient = Patient.find(params[:id])
  end

  def patient_details
    @patient = Patient.find(params[:id])
    render 'patient_details'
  end

private

  def patient_params
    params.require(:patient).permit(:name, :email_id, :problem)
  end
  
end

app/controllers/physicians_controller.rb
class PhysiciansController < ApplicationController

  def index
    @physicians=Physician.all
  end
  
  def new
    @physician=Physician.new
  end

  def create
    @physician=Physician.new()
    @physician.name = params[:physician][:name]
    @physician.speciality = params[:physician][:speciality]
    if @physician.save
    redirect_to @physician
    else
    render 'new'
    end
  end
 
  def see_patients
    @physician = Physician.find(params[:id]) 
    render 'see patients'
  end

  def show
    @physician = Physician.find(params[:id])
  end

  def check
    render :text => "got it"
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

def index

  logger.info p params
  Patient.delete_file
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/associates_helper.rb
module AssociatesHelper
end

app/helpers/component_helper.rb
module ComponentHelper


def component_table_list(args)
  default_args = {
      :decoration => "app/views/patients/index.html.erb"
  }
  args= default_args.merge(args)
  sr_render_widget(args)
end

  end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/physicians_helper.rb
module PhysiciansHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/appointments/index.html.erb
<h1> Appointments </h1>
<%@appointments=Appointment.last(10).paginate(:page => params[:page], :per_page => 2)%>
<table>
  <tr>
    <th>Id</th>
    <th>Physician ID</th>
    <th>Patient ID</th>
    <th>Appointment Date</th>
    <th>Created At</th>
    <th>Updated At</th>
  </tr>

  <% @appointments.each do |appointment| %>
    <tr>
      <td><%= appointment.id %></td>
      <td><%= appointment.physician_id %></td>
      <td><%= appointment.patient_id %></td>
      <td><%= appointment.appointment_date %></td>
      <td><%= appointment.created_at %></td>
      <td><%= appointment.updated_at %></td>
    </tr>
  <% end %>


<%= link_to 'Back', physicians_path %>

</table>

<%#= will_paginate @appointments %>
<%=will_paginate(@appointments,{:previous_label=>"Previous",:next_label=>"Next",:inner_window=>1,:outer_window=>0}) %>

app/views/associates/index.html.erb
<h1> List of Enrollments </h1>

<%= link_to "Enrollment", new_associate_path %>

app/views/associates/new.html.erb
<h1> Want to enroll</h1>
<%= form_for :association, url: associates_path do |f| %>
<p>
<%= f.label :physician_id %>
<%= f.number_field :physician_id %>
</p> 
<p>
<%= f.label :physician_id %>
<%= f.select :physician_id, options_for_select(%w[a b c d e f]) %> 
</p>
<P>
<%= f.submit "Enroll"%>
</p>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Association</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/orders/index.html.erb
<%= form_tag "/orders/status" do%>



<%end%>

app/views/patients/component_table_list.html.erb
<%=component_table_list(component_hash)%>

app/views/patients/edit.html.erb
<%= form_for :patient, url: patient_path(@patient), method: :patch do |f| %>

    <p>
      <%= f.label :name %>
      <%= f.text_field :name %>
    </p>

    <p>
      <%= f.label :problem %>
      <%= f.text_area :problem %>
    </p>

    <p>
      <%=f.label :email_id %>
      <%=f.text_field :email_id %>
    </p>

    <p>
      <%= f.label :select_physician %>
      <%= collection_select(:physician, :physician_id, Physician.all, :id, :name,
                            {:prompt => 'Please select Physician'}) %>


    </p>

    <p>
      <%= f.submit %>
    </p>
<% end %>

<%= link_to 'Back', patients_path %>

app/views/patients/index.html.erb
<h1> Patient List </h1>

<%= form_tag patients_path, :method => :get do %>
    <p>
      <%= text_field_tag :search, params[:search] %>
      <%= submit_tag "Search", :name => nil %>
<% end %>


<%= link_to 'New Patient', new_patient_path %>


<!--<div>-->
 <!---->
  <!--<%#= component_table_list SrComponent.find_component_by_name('ClassifierList') %>-->
<!--</div>-->
<table>
  <tr>
    <th>Id</th>
    <th>Name</th>
    <th>Problem</th>
    <th>Selected Physician</th>
    <th>Created At</th>
    <th>Updated At</th>
  </tr>

  <% @patients.each do |patient| %>
    <tr>

      <td><%= patient.id %></td>
      <td><%= best_in_place patient, :name, :classes => 'highlight_on_success'%></td>



      <td><%#= patient.problem %></td>
      <td><%#= Physician.find(patient.select_physician).name %></td>
      <td><%= patient.created_at %></td>
      <td><%= patient.updated_at %></td>
      <td> <%= link_to "edit", edit_patient_path(patient) %></td>
    </tr>
  <% end %>


<%= link_to 'Back', patients_path %>

</table>

    <!--<div>
      <%#= component_table_list SrComponent.find_component_by_name('ClassifierList') %>
   <!-- </div>

    <%#=content_tag(:div, @campaign.errors.blank? ? nil : render(:partial => 'new_classifier'), :id => 'new_classifier', :style => 'margin-top:11px;' ) %>


    <%#= content_tag(:div, link_to("Add #{ classifier.name }", { :action=> 'new_classifier', :classifier_id => params[:classifier_id], :campaign_id => params[:campaign_id] },"data-update"=>"new_classifier","data-paramtype"=>"get_href",:class=>"ajax_form_call"), :class => 'button')%>
-->
<script>
   // $('.highlight_on_success').bind("ajax:success", function(){$(this).closest('tr').effect('highlight'));});
</script>

app/views/patients/new.html.erb
<h1>New Patient</h1>
<%= form_for :patient, url: patients_path do |f| %>

<p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>

<p>
    <%#= f.label :problem %>
    <%#= f.text_area :problem %>
  </p>

<p>
    <%#=f.label :email_id %>
    <%#=f.text_field :email_id %>
</p>

<p>
<%= f.label :select_physician %>
<%= collection_select(:physician, :physician_id, Physician.all, :id, :name,
                 {:prompt => 'Please select Physician'}) %>


</p> 
 
  <p>
    <%= f.submit %>
  </p>
<% end %>
<%= select_tag "export_setup[export_frequency]", options_for_select(SINGLE_QUEST_VIEW_TYPE.collect{|u| u}) %>

<%= link_to 'Back', patients_path %>

app/views/patients/patient_details.html.erb
<h1>Patient Detail</h1>
<%debugger%>
<p>
<strong>Name:</strong>
<%= @patient.name %>

</p>

<p>
<strong>Problem:</strong>
<%= @patient.problem %>
</p>

app/views/patients/show.html.erb
<p>
<strong>Name:</strong>
<%= @patient.name %>

</p>

<p>
<strong>Problem:</strong>
<%= @patient.problem %>
</p>

<p>
<strong>Physician_Selected:</strong>
<%= @patient.select_physician %>
</p>

app/views/physicians/index.html.erb
<h1> Physician List </h1>


<%= link_to 'New Physician', new_physician_path %>

<table>
  <tr>
    <th>Id</th>
    <th>Name</th>
    <th>Speciality</th>
    <th>Created At</th>
    <th>Updated At</th>
  </tr>

  <% @physicians.each do |physician| %>
    <tr>
      <td><%= physician.id %></td>
      <td><%= physician.name %></td>
      <td><%= physician.speciality %></td>
      <td><%= physician.created_at %></td>
      <td><%= physician.updated_at %></td>
      <td><%#= link_to 'See_Patients', physicians_see_patients_path %> </td>
      <td><%= link_to 'See_Patients', "/physicians_see_patients/#{physician.id}" %> </td>
    </tr>
  <% end %>


</table>

app/views/physicians/new.html.erb
<h1>New Physician</h1>
<%= form_for :physician, url: physicians_path do |f| %>

<p>
 <%= f.label :name %><br>
 <%= f.text_field :name %>
</p>
<p>
 <%= f.label :speciality %><br>
 <%= f.text_field :speciality %>
</p>
 
<p>
 <%= f.submit %>
</p>
<% end %>
 
<%= link_to 'Back', physicians_path %>

<%form_tag %>

app/views/physicians/see patients.html.erb
<h1>Patient List</h1>

<table>
  <tr>
     <th>Patient ID</th>
     <th>Patient Name</th>
     <th>Details</th>
  </tr>

  
  <% @physician.appointments.each do |physician| %>

<tr>
     <td><%= physician.patient_id %></td>
     <td><%= physician.patient.name %></td>
<% debugger %>
     <td><%= link_to 'Patient Details' , "/patients_patient_details/#{physician.patient_id}" %> </td>
  </tr>
 <% end %>
</table>

app/views/physicians/show.html.erb
<p>
<strong>Name:</strong>
<%= @physician.name %>
</p>
<p>
<strong>Speciality:</strong>
<%= @physician.speciality %>
</p>

app/views/welcome/index.html.erb
<%=link_to "Appointments", 'javascript:void(0)', :class => "appoint" %>
<%= link_to "Patients", patients_path%>
<%=link_to "Physicians", physicians_path %>
<%#=link_to "check fast", check_path %>
<%= link_to "export_xml", 'javascript:void(0)', :class => 'export_it'%>
<%= link_to "Export Double Ajax", 'javascript:void(0)', :class => 'double_ajax'%>

<!-- https://www.create.net/support/218-how-to-pin-point-multiple-locations-on-google-maps.html -->
<!--<iframe src="https://mapsengine.google.com/map/embed?mid=z1InabQWXKac.keI5nIKpQoK0" width="640" height="480"></iframe>-->
<script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?v=3&amp;sensor=false"></script>
<div id="map_div" style="height: 400px;"></div>

<style>
    body {
        margin: 0;
        padding: 0;
        font: 12px sans-serif;
    }
    h1, p {
        margin: 0;
        padding: 0;
    }
</style>
<script>
    /*
     * declare map as a global variable
     */
    var map;

    /*
     * use google maps api built-in mechanism to attach dom events
     */
    google.maps.event.addDomListener(window, "load", function () {

        /*
         * create map
         */
        var map = new google.maps.Map(document.getElementById("map_div"), {
            center: new google.maps.LatLng(33.808678, -117.918921),
            zoom: 14,
            mapTypeId: google.maps.MapTypeId.ROADMAP
        });

        /*
         * create infowindow (which will be used by markers)
         */
        var infoWindow = new google.maps.InfoWindow();

        /*
         * marker creater function (acts as a closure for html parameter)
         */
        function createMarker(options, html) {
            var marker = new google.maps.Marker(options);
            if (html) {
                google.maps.event.addListener(marker, "click", function () {
                    infoWindow.setContent(html);
                    infoWindow.open(options.map, this);
                });
            }
            return marker;
        }

        /*
         * add markers to map
         */
        var marker0 = createMarker({
            position: new google.maps.LatLng(33.808678, -117.918921),
            map: map,
            icon: "http://1.bp.blogspot.com/_GZzKwf6g1o8/S6xwK6CSghI/AAAAAAAAA98/_iA3r4Ehclk/s1600/marker-green.png"
        }, "<h1>Marker 0</h1><p>This is the home marker.</p>");

        var marker1 = createMarker({
            position: new google.maps.LatLng(33.818038, -117.928492),
            map: map
        }, "<h1>Marker 1</h1><p>This is marker 1</p>");

        var marker2 = createMarker({
            position: new google.maps.LatLng(33.803333, -117.915278),
            map: map
        }, "<h1>Marker 2</h1><p>This is marker 2</p>");
    });

</script>

<script>

    $('.double_ajax').click(function(){

        var a = "testing";
        $.ajax({
            type: "POST",
            dataType: "html",
            url: "/export_ajax",
            data: "check=" + a,
            beforeSend: function (xhr) {
                xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'))
            },
            success: function (data) {
                console.log(data);
                next_ajax_func(data)
            }
        })

    });


    var next_ajax_func = function(data) {
        console.log(data);
        $.ajax({
            type: "POST",
            dataType: "html",
            url: "/to_check",
            beforeSend: function (xhr) {
                xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'))
            },
            success: function (data) {
                console.log(data);
                createInterval(funca,data,5000);

            }
        });
    };

    function funca(data,intercast) {
        console.log("second place");
        console.log(intercast);
        $.ajax({
            type: "POST",
            dataType: "html",
            url: "/to_clear_it",
            beforeSend: function (xhr) {
                xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'))
            },
            success: function (data) {
                console.log(data);
                console.log(intercast);
                clearInterval(intercast);
            }
        });
    }

    function createInterval(f,data,interval)
    {
        var intercast  = setInterval(function () {
            f(data,intercast);
            console.log("im here");
        }, interval);
    }


    $('.appoint').click(function(){
        $.ajax({
            type: "GET",
            dataType: "xml",

            url: "/appointments"

        })
    });
</script>